export default {
  USER_LOADED: 'USER_LOADED',
  SUBMIT: 'SUBMIT',
  SUBMITTED: 'SUBMITTED',
  OFFER_CHANGE: 'OFFER_CHANGE',
  CREDIT_CARD_CHANGE: 'CREDIT_CARD_CHANGE',
  OFFER_SUBMIT: 'OFFER_SUBMIT',
};
